### ISSUE TITLE
Autoconf fails

### ISSUE THREAD

**Issue by dsg1963** [m3u8-segmenter/m3u8-segmenter#16]
Hi John,

I am trying to build the segmenter on CentOS 5.7. I installed autoconf 2.68, but when I run it on the segmenter project I get the following error:
configure.ac:16: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

I've looked at the doc, but I know nothing of autoconf and it's not making sense to me. Can you help me out so I can build the project?

Thank you.

Don

**Comment by startx2** [comment]
autoreconf -f -i -Wall,no-obsolete

does the trick for me ( though i cannot excactly explain it )

**Comment by johnf** [comment]
I can't replicate this so closing
