### ISSUE TITLE
Compile fails on ubuntu 10.04 LTS

### ISSUE THREAD

**Issue by htrendev** [m3u8-segmenter/m3u8-segmenter#2]
The source fails to compile on ubuntu 10.04. This patch http://pastebin.com/JFsuxxPK resolves the problem.

Fix was copied from the code at https://github.com/carsonmcdonald/HTTP-Live-Video-Stream-Segmenter-and-Distributor/blob/master/live_segmenter.c

**Comment by johnf** [comment]
Thanks for the patch!

**Comment by johnf** [comment]
Fixed in ce1faf5
