### ISSUE TITLE
No compiling with latest Ffmpeg

### ISSUE THREAD

**Issue by fingcmo** [m3u8-segmenter/m3u8-segmenter#22]
This is my ffmpeg version:

$ ffmpeg -version
ffmpeg version N-39609-g50ec8a2
built on Apr  7 2012 13:07:46 with gcc 4.6.1
configuration: --enable-gpl --enable-gray --enable-runtime-cpudetect --enable-bzlib --enable-gnutls --enable-libass --enable-libcelt --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libcdio --enable-libdc1394 --enable-libdirac --enable-libfaac --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libnut --enable-libopenjpeg --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libv4l2 --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-openal --enable-openssl --enable-zlib --enable-nonfree --enable-version3 --enable-x11grab
libavutil      51. 45.100 / 51. 45.100
libavcodec     54. 13.100 / 54. 13.100
libavformat    54.  3.100 / 54.  3.100
libavdevice    53.  4.100 / 53.  4.100
libavfilter     2. 67.101 /  2. 67.101
libswscale      2.  1.100 /  2.  1.100
libswresample   0. 10.100 /  0. 10.100
libpostproc    52.  0.100 / 52.  0.100

This is what I did to try to download and compile it:

$ mkdir mygits
$ cd mygits
$ git clone https://github.com/johnf/m3u8-segmenter.git
$ cd m3u8-segmenter/
$ ls -l
$ autoconf
$ autoreconf -f -i -Wall,no-obsolete
$ ./configure
$ make

This is the error I get:

~/mygits/m3u8-segmenter$ make
Making all in tests
make[1]: Entering directory `/home/me/mygits/m3u8-segmenter/tests'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/me/mygits/m3u8-segmenter/tests'
make[1]: Entering directory`/home/me/mygits/m3u8-segmenter'
gcc -DPACKAGE_NAME=\"m3u8-segmenter\" -DPACKAGE_TARNAME=\"m3u8-segmenter\" -DPACKAGE_VERSION=\"0.3\" -DPACKAGE_STRING=\"m3u8-segmenter\ 0.3\" -DPACKAGE_BUGREPORT=\"http://github.com/johnf/m3u8-segmenter/issues\" -DPACKAGE_URL=\"http://m3u8-segmenter.inodes.org\" -DPACKAGE=\"m3u8-segmenter\" -DVERSION=\"0.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SIGNAL_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -I/usr/local/include   -g -O2 -Wall -Wextra -Wdeclaration-after-statement -Wpointer-arith -funsigned-char -Werror -Wall -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wnested-externs -Wshadow -Wbad-function-cast -Wwrite-strings  -MT m3u8_segmenter-m3u8-segmenter.o -MD -MP -MF .deps/m3u8_segmenter-m3u8-segmenter.Tpo -c -o m3u8_segmenter-m3u8-segmenter.o `test -f 'm3u8-segmenter.c' || echo './'`m3u8-segmenter.c
m3u8-segmenter.c: In function ‘add_output_stream’:
m3u8-segmenter.c:58:5: error: ‘av_new_stream’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:1543) [-Werror=deprecated-declarations]
m3u8-segmenter.c: In function ‘main’:
m3u8-segmenter.c:341:5: error: ‘av_find_stream_info’ is deprecated (declared at /usr/local/include/libavformat/avformat.h:1343) [-Werror=deprecated-declarations]
m3u8-segmenter.c:388:7: error: ‘avcodec_open’ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:3723) [-Werror=deprecated-declarations]
m3u8-segmenter.c:395:45: error: ‘URL_WRONLY’ undeclared (first use in this function)
m3u8-segmenter.c:395:45: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors

make[1]: **\* [m3u8_segmenter-m3u8-segmenter.o] Error 1
make[1]: Leaving directory `/home/me/mygits/m3u8-segmenter'
make: **\* [all-recursive] Error 1
me@mbp-ubuntu:~/mygits/m3u8-segmenter$

Please let me know what version of Ffmpeg and libraries  are known to work,
Thanks,

**Comment by SovGVD** [comment]
sorry, don't know how to make patch, so try this file with a lot of fixes for new ffmpeg: http://nekaka.com/d/vmN0Ex3Jef

**Comment by fingcmo** [comment]
Thanks, your code compiles. Now let me test it out!

Ad.

**Comment by fingcmo** [comment]
I tried to run as ffolows:

ffmpeg -i big_buck_bunny.ogv -f mpegts - | m3u8-segmenter -i - -d 10 -p big_buck_bunny -m big_buck.m3u8 -u http://inodes.org/bigbuck/

And I got this error:

m3u8-segmenter: relocation error: /usr/local/lib/libavcodec.so.54: symbol av_get_default_channel_layout, version LIBAVUTIL_51 not defined in file libavutil.so.51 with link time reference

Let me know if you know of a quick way to kill that.

Ad.

**Comment by SovGVD** [comment]
Sorry, i don't know, but i build ffmpeg from latest sources and with --prefix=/usr

**Comment by johnf** [comment]
This should have been fixed in latest trunk. New release shortly
