### ISSUE TITLE
v1.0 does not compile with ffmpeg 0.11.1 (re-open)

### ISSUE THREAD

**Issue by bcoiffe** [m3u8-segmenter/m3u8-segmenter#25]
~/johnf-m3u8-segmenter-dc29d5b$ aclocal
~/johnf-m3u8-segmenter-dc29d5b$ automake -ac
~/johnf-m3u8-segmenter-dc29d5b$ autoconf
~/johnf-m3u8-segmenter-dc29d5b$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for sys/types.h... (cached) yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for memmove... yes
checking for memset... yes
checking for strrchr... yes
checking for strtol... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FFMPEG... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tests/Makefile
config.status: executing depfiles commands
pi@raspberrypi:~/johnf-m3u8-segmenter-dc29d5b$ make
Making all in tests
make[1]: Entering directory `/home/pi/johnf-m3u8-segmenter-dc29d5b/tests'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/pi/johnf-m3u8-segmenter-dc29d5b/tests'
make[1]: Entering directory`/home/pi/johnf-m3u8-segmenter-dc29d5b'
gcc -DPACKAGE_NAME=\"m3u8-segmenter\" -DPACKAGE_TARNAME=\"m3u8-segmenter\" -DPACKAGE_VERSION=\"0.3\" -DPACKAGE_STRING=\"m3u8-segmenter\ 0.3\" -DPACKAGE_BUGREPORT=\"http://github.com/johnf/m3u8-segmenter/issues\" -DPACKAGE_URL=\"http://m3u8-segmenter.inodes.org\" -DPACKAGE=\"m3u8-segmenter\" -DVERSION=\"0.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SIGNAL_H=1 -DHAVE_GETOPT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_STRRCHR=1 -DHAVE_STRTOL=1 -I.    -I/usr/local/include   -g -O2 -Wall -Wextra -Wdeclaration-after-statement -Wpointer-arith -funsigned-char -Werror -Wall -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wnested-externs -Wshadow -Wbad-function-cast -Wwrite-strings  -MT m3u8_segmenter-m3u8-segmenter.o -MD -MP -MF .deps/m3u8_segmenter-m3u8-segmenter.Tpo -c -o m3u8_segmenter-m3u8-segmenter.o `test -f 'm3u8-segmenter.c' || echo './'`m3u8-segmenter.c
m3u8-segmenter.c: In function ‘main’:
m3u8-segmenter.c:397: error: ‘URL_WRONLY’ undeclared (first use in this function)
m3u8-segmenter.c:397: error: (Each undeclared identifier is reported only once
m3u8-segmenter.c:397: error: for each function it appears in.)
make[1]: **\* [m3u8_segmenter-m3u8-segmenter.o] Error 1
make[1]: Leaving directory `/home/pi/johnf-m3u8-segmenter-dc29d5b'
make: **\* [all-recursive] Error 1
~/johnf-m3u8-segmenter-dc29d5b$ ffmpeg -version
ffmpeg version 0.11.1
built on Jul  4 2012 13:56:57 with gcc 4.4.5
configuration: --enable-gpl --enable-nonfree --enable-libfaac --enable-libmp3lame
libavutil      51. 54.100 / 51. 54.100
libavcodec     54. 23.100 / 54. 23.100
libavformat    54.  6.100 / 54.  6.100
libavdevice    54.  0.100 / 54.  0.100
libavfilter     2. 77.100 /  2. 77.100
libswscale      2.  1.100 /  2.  1.100
libswresample   0. 15.100 /  0. 15.100
libpostproc    52.  0.100 / 52.  0.100

**Comment by Xris01** [comment]
Same here, still having m3u8-segmenter.c:397: error: ‘URL_WRONLY’ undeclared (first use in this function) with the latest ffmpeg from trunk :

ffmpeg version N-42291-g6936111
built on Jul  6 2012 11:34:33 with gcc 4.4.5
configuration: --prefix=/opt/mediatech/multimedia --extra-cflags=-I/opt/mediatech/multimedia/include --extra-ldflags=-L/opt/mediatech/multimedia/lib --enable-shared --cc=ccache cc --disable-altivec --
disable-armv5te --disable-armv6 --disable-armv6t2 --disable-stripping --enable-gpl --enable-libfaac --enable-libgsm --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-l
ibopenjpeg --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-nonfree --enable-postproc --enable-pthreads --ena
ble-version3 --enable-librtmp
libavutil      51. 64.100 / 51. 64.100
libavcodec     54. 33.100 / 54. 33.100
libavformat    54. 15.100 / 54. 15.100
libavdevice    54.  1.100 / 54.  1.100
libavfilter     3.  0.101 /  3.  0.101
libswscale      2.  1.100 /  2.  1.100
libswresample   0. 15.100 /  0. 15.100
libpostproc    52.  0.100 / 52.  0.100

**Comment by johnf** [comment]
Should be fixed by 19640e94e75e76845584d2b7cb8d612a988012a7

**Comment by bcoiffe** [comment]
Almost :-)!
You left one occurence l.470.
