### ISSUE TITLE
New maintainer or close down project

### ISSUE THREAD

**Issue by johnf** [m3u8-segmenter/m3u8-segmenter#32]
Howdy,

I don't really have time to maintain this any more and since ffmpeg now seens to contain this functionality (see #17) then I'm not sure if there is much point.

@midnox you seem to have the most active branch, are you interested in taking over maintainership?

**Comment by johnf** [comment]
@jaffa4 @d-a-n @ghost You all have pending pull requests. Do you have any interest in taking over this project?

**Comment by jaffa4** [comment]
I use m3u8-segmenter because it works. ffmpeg does not...always

**Comment by d-a-n** [comment]
Hi John,

I would if @midnox doesn't want to.

Cheers
Dan

**Comment by johnf** [comment]
Hi @d-a-n you still interested. Not sure why I didn't notice this a few years ago and hand it over

or @ghost @elkq @dkavraal
