### ISSUE TITLE
How to build? build fails in ubuntu 10.04(32 bit) and 11.04(64 bit)

### ISSUE THREAD

**Issue by georgel2004** [m3u8-segmenter/m3u8-segmenter#5]
Hello,

Is there any write up on how to build m3u8-segmenter and how to use it?

It will be nice if the home page atleast  mentions where it might work properly (windows, linux etc)

Thanks
George

P.S make output

gcc -g -O -Wall -Wstrict-prototypes -Wmissing-prototypes -Waggregate-return -Wcast-align -Wcast-qual -Wnested-externs -Wshadow -Wbad-function-cast -Wwrite-strings -Werror m3u8-segmenter.c -o m3u8-segmenter -lavformat -lavcodec -lavutil
m3u8-segmenter.c: In function âadd_output_streamâ:
m3u8-segmenter.c:82:14: error: âCODEC_TYPE_AUDIOâ undeclared (first use in this function)
m3u8-segmenter.c:82:14: note: each undeclared identifier is reported only once for each function it appears in
m3u8-segmenter.c:94:14: error: âCODEC_TYPE_VIDEOâ undeclared (first use in this function)
cc1: warnings being treated as errors
m3u8-segmenter.c: In function âmainâ:
m3u8-segmenter.c:338:5: error: âav_open_input_fileâ is deprecated (declared at /usr/local/include/libavformat/avformat.h:1105)
m3u8-segmenter.c:352:5: error: implicit declaration of function âguess_formatâ
m3u8-segmenter.c:352:5: error: nested extern declaration of âguess_formatâ
m3u8-segmenter.c:352:10: error: assignment makes pointer from integer without a cast
m3u8-segmenter.c:371:18: error: âCODEC_TYPE_VIDEOâ undeclared (first use in this function)
m3u8-segmenter.c:376:18: error: âCODEC_TYPE_AUDIOâ undeclared (first use in this function)
m3u8-segmenter.c:387:5: error: âav_set_parametersâ is deprecated (declared at /usr/local/include/libavformat/avformat.h:1449)
m3u8-segmenter.c:392:5: error: âdump_formatâ is deprecated (declared at /usr/local/include/libavformat/avformat.h:1592)
m3u8-segmenter.c:400:7: error: âavcodec_openâ is deprecated (declared at /usr/local/include/libavcodec/avcodec.h:3749)
m3u8-segmenter.c:406:5: error: âurl_fopenâ is deprecated (declared at /usr/local/include/libavformat/avio.h:279)
m3u8-segmenter.c:411:5: error: âav_write_headerâ is deprecated (declared at /usr/local/include/libavformat/avformat.h:1507)
m3u8-segmenter.c:444:67: error: âPKT_FLAG_KEYâ undeclared (first use in this function)
m3u8-segmenter.c:455:13: error: âput_flush_packetâ is deprecated (declared at /usr/local/include/libavformat/avio.h:289)
m3u8-segmenter.c:456:13: error: âurl_fcloseâ is deprecated (declared at /usr/local/include/libavformat/avio.h:280)
m3u8-segmenter.c:476:13: error: âurl_fopenâ is deprecated (declared at /usr/local/include/libavformat/avio.h:279)
m3u8-segmenter.c:482:13: error: âav_write_headerâ is deprecated (declared at /usr/local/include/libavformat/avformat.h:1507)
m3u8-segmenter.c:514:5: error: âurl_fcloseâ is deprecated (declared at /usr/local/include/libavformat/avio.h:280)
make: **\* [all] Error 1

**Comment by georgel2004** [comment]
After several trials, I am able to compile the live_segmenter from carson mcdonald.
After that i tried to compile m3u8-segmenter and ended up with 1 error now.

 gcc -v -Wall -g m3u8-segmenter.c -o m3u8-segmenter \

> ```
> -lavformat -lavcodec -lavutil -lvorbis -ltheora\
> -lbz2 -lm -lz -lfaac -lmp3lame \
> -lx264 \
> -I/tmp/ffmpeg/include \
> -L/tmp/ffmpeg/lib \
> ```
> 
> -std=c99
> Using built-in specs.
> COLLECT_GCC=gcc
> COLLECT_LTO_WRAPPER=/usr/lib/x86_64-linux-gnu/gcc/x86_64-linux-gnu/4.5.2/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.5.2-8ubuntu4' --with-bugurl=file:///usr/share/doc/gcc-4.5/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.5 --enable-shared --enable-multiarch --with-multiarch-defaults=x86_64-linux-gnu --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib/x86_64-linux-gnu --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.5 --libdir=/usr/lib/x86_64-linux-gnu --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-plugin --enable-gold --enable-ld=default --with-plugin-ld=ld.gold --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 4.5.2 (Ubuntu/Linaro 4.5.2-8ubuntu4)
> COLLECT_GCC_OPTIONS='-v' '-Wall' '-g' '-o' 'm3u8-segmenter' '-I/tmp/ffmpeg/include' '-L/tmp/ffmpeg/lib' '-std=c99' '-mtune=generic' '-march=x86-64'
>  /usr/lib/x86_64-linux-gnu/gcc/x86_64-linux-gnu/4.5.2/cc1 -quiet -v -I/tmp/ffmpeg/include m3u8-segmenter.c -D_FORTIFY_SOURCE=2 -quiet -dumpbase m3u8-segmenter.c -mtune=generic -march=x86-64 -auxbase m3u8-segmenter -g -Wall -std=c99 -version -fstack-protector -o /tmp/ccLlhpxR.s
> GNU C (Ubuntu/Linaro 4.5.2-8ubuntu4) version 4.5.2 (x86_64-linux-gnu)
>         compiled by GNU C version 4.5.2, GMP version 4.3.2, MPFR version 3.0.0-p8, MPC version 0.9
> GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
> ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
> ignoring nonexistent directory "/usr/lib/x86_64-linux-gnu/gcc/x86_64-linux-gnu/4.5.2/../../../../../x86_64-linux-gnu/include"
> #include "..." search starts here:
> #include <...> search starts here:
>  /tmp/ffmpeg/include
>  /usr/local/include
>  /usr/lib/x86_64-linux-gnu/gcc/x86_64-linux-gnu/4.5.2/include
>  /usr/lib/x86_64-linux-gnu/gcc/x86_64-linux-gnu/4.5.2/include-fixed
>  /usr/include/x86_64-linux-gnu
>  /usr/include
> End of search list.
> GNU C (Ubuntu/Linaro 4.5.2-8ubuntu4) version 4.5.2 (x86_64-linux-gnu)
>         compiled by GNU C version 4.5.2, GMP version 4.3.2, MPFR version 3.0.0-p8, MPC version 0.9
> GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
> Compiler executable checksum: 9755ab75799195519479ef699703b13b
> m3u8-segmenter.c: In function âmainâ:
> m3u8-segmenter.c:211:22: error: storage size of âactâ isnât known
> m3u8-segmenter.c:422:5: warning: implicit declaration of function âsigactionâ
> m3u8-segmenter.c:211:22: warning: unused variable âactâ

**Comment by johnf** [comment]
Your first problem is because you didn't have the ffmpeg libraries installed on your system.

The current one come from adding --std=c99. Try dropping that
