### ISSUE TITLE
segmenter disobeys -d duration (also default value is not obeyed)

### ISSUE THREAD

**Issue by rakesh8116** [m3u8-segmenter/m3u8-segmenter#6]
Hi Johnf,

I am using your latest segmenter along with latest stable ffmpeg release (0.8).  I have observed that segmenter disobeys -d options and generates segments of variable length. Even the default value (10) for -d option genrating chunks of variable length.

Example 1:
ffmpeg -i out.ts    => Duration: 00:00:48.00 secs

m3u8-segmenter -i out.ts  -d 5 -p file  -m index_main.m3u8 -u "";

generates chunks of below sizes.
file-1.ts  =>   4.16 secs      file-2.ts  =>   6.32 secs    file-3.ts => 10.00 secs       file-4.ts => 12.40 secs          file-5.ts =>  7.98 secs      file-6.ts =>   7.56

Example 2: (segmenter run with default option, removed -d option)

m3u8-segmenter -i out.ts  -p file  -m index_main.m3u8 -u "";

file-1.ts  =>  10.04 secs   file-2.ts => 12.36 secs     file-3.ts  =>  10.12 secs   file-4.ts   =>15.48 secs 

Please let me know is this usage issue or bug in the segmenter code?

Thanks a lot
Rakesh

PS: 
I have done below changes to compile latest segmenter with ffmpeg 0.8

changed:

CODEC_TYPE_AUDIO => AVMEDIA_TYPE_AUDIO
CODEC_TYPE_VIDEO => AVMEDIA_TYPE_VIDEO
PKT_FLAG_KEY  => AV_PKT_FLAG_KEY

**Comment by rakesh8116** [comment]
This is ffmpeg version I am using. 

./ffmpeg -version 

ffmpeg 0.8
libavutil    51.  9. 1 / 51.  9. 1
libavcodec   53.  7. 0 / 53.  7. 0
libavformat  53.  4. 0 / 53.  4. 0
libavdevice  53.  1. 1 / 53.  1. 1
libavfilter   2. 23. 0 /  2. 23. 0
libswscale    2.  0. 0 /  2.  0. 0
libpostproc  51.  2. 0 / 51.  2. 0

By mistake I pressed close issue, reopening it.

**Comment by johnf** [comment]
I tested this with ffmpeg 0.6 and this seems to work fine. Could you try with the older version of the library and see if you have any problems. I haven't tested with newer versions since I'm waiting to see how the ffmpeg vs libav fork pans out before deciding which to support.

**Comment by rakesh8116** [comment]
Hi johnf,
The segmenter works fine till ffmpeg-0.6.2.   However later stable releases of ffmpeg like ffmpeg 0.7.1 and ffmpeg 0.8 comes with lot of fixes and also features like audio channels support till 8 channels.
Ideally segmenter must work with them(ffmpeg 0.7.1 and 0.8) as well as they are stable releases and very much into use now. I have been huge fan of segmenter and its widely used as well. But its limitation to support ffmpeg till 0.6.2 is a blemish I should add humbly for this otherwise a wonderful piece of code.

Do you have any future plans to support the higher and stable version of ffmpeg and till when? I would die to listen yes and very soon.

**Comment by johnf** [comment]
@rakesh8116 I've added support for 0.7.1 and 0.8. Let me know if you have any problems. Durations also seem to work ok. If they don't for you could you pleas share your input file.
